### ISSUE TITLE
Log out doesn't seem to actually log user out

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/open-management-portal-frontend#11]
When attempting to test the frontend/backend -- I initially logged in as the admin user and tested things out. After reading some additional comments on this issue, I see that this was supposed to be tested as a different user (`tom`). So I attempted to log out, which brings me back to the initial sign in screen where I click on `Log in using SSO`. However it then drops me directly back into the app -- as what I'm assuming was my previously logged in user as I'm never actually prompted to log in as a new user.

**Comment by jacobsee** [comment]
Yep, definitely need to address this. The problem is that there are _two_ sessions at play: OAuth redirects the user to SSO where a session is opened between SSO and the user, and forwarded back to the app with a token, where a second session is opened between this app and the user. Logout currently destroys the second session, but leaves the first one open. The auth module being used here needs to be extended to call SSO's `END_SESSION_ENDPOINT`: https://github.com/nuxt-community/auth-module/blob/e21de05cdf65deea67dbc1215ccb08673a7232bb/lib/schemes/oauth2.js#L70
